### PR TITLE
PSR-12 linting, move Uuid into its own namespace, add PSR-4

### PR DESCRIPTION
**Pull request by robbieaverill**
Summary of changes:

* Automated PSR-12 linting, add phpcs ruleset
* Reduce line length to 120 chars
* Add PSR-4 autoloader (closes #82) and remove nested class declarations inside `namespace Raygun4php { ... }`
* Remove readme instructions for manual installation, and require calls - use Composer
* Add editorconfig file for IDE formatting
* Adds PSR-12 linting checks (with one exclusion: method naming - we can break this in 2.x-dev, but it can be done in another PR) to Travis CI builds
* Update minimum PHP version to 7.1, update PHPUnit to ^7.0
* Remove RaygunExceptionMessage::GetClassName() since it is unused

I'd suggest this should be a new minor release, or potentially even a new major release. I don't think I've broken any APIs but might better to be safe than sorry.

### CODE REVIEW

**Comment by robbieaverill** [comment]
Since we're going to treat this as a breaking change into 2.x-dev (master), I've also increased the minimum PHP version to 7.1 (since 5.6 and 7.0 are EOL), and updated PHPUnit to ^7.5

**Comment by robbieaverill** [comment]
@sminnee I know it's a bit of a bertha, but fancy a review when you get a chance? Don't forget `?w=1` on the diff view to ignore whitespace ;)

**Comment by anfly0** [comment]
Is this going to be merged?
I have some ideas for refactoring parts of this project and would be happy to contribute.
But since this pr would bump the major version, and my ideas would most certainly break parts of the current API I don't want to put in too much effort in before this pr merged.

**Comment by robbieaverill** [comment]
Given that this has been lurking around for a while now, I'm going to merge it.  @anfly0 you can use 2.x-dev and contribute breaking changes to the master branch. If you're breaking or changing APIs, can you please note anything important in the changelog section of the readme?

**Pull request merged**
