### PR TITLE
Exception line/file of where thrown plus add shortcut to composer for running tests with `composer test

### LINKED ISSUE #147: Raygun doesn't actually report the file name and line number of the actual error, which is the most important part.
Identical to #72 

I have to do something like this to even get the data to Raygun.

```php
$raygunClient = new RaygunClient( $transport );
            $raygunClient->SendException(
                $exception,
                ['service' => env('APP_NAME' )],
                [
                    'file' => $exception->getFile(),
                    'line' => $exception->getLine()
                ]
            );
```

but then it's stuffed into the "Custom" tab and isn't part of the stack trace.

Something as simple as this change to `BuildStackTrace` in the `RayGunExceptionMessage` class  would put file and line into the stack trace reported to RayGun.

```php
    private function BuildStackTrace($exception)
    {
        $traces = $exception->getTrace();
        $lines = array();

        $line = new RaygunExceptionTraceLineMessage();
        $line->FileName = $exception->getFile();
        $line->LineNumber = $exception->getLine();
        $lines[] = $line;

        foreach ($traces as $trace) {
            $lines[] = $this->BuildLine($trace);
        }

        $this->StackTrace = $lines;
    }
```

### PR DESCRIPTION
**Pull request by treehousetim**
easier unit test running. instead of vendor/bin/phpunit
add more complete exception payload to message

Fixes #147

### CODE REVIEW

**Review by robbieaverill — APPROVED** [review]
Looks reasonable to me. I've requested a review from one of the Raygun team too.

**Comment by Deacon-McIntyre** [comment]
Thanks for taking a look @robbieaverill , we'll get this released this week 👍

**Comment by Deacon-McIntyre** [comment]
Hi @treehousetim, thanks for submitting this! During testing I noticed that `RaygunExceptionMessage` is also used by the `SendError` function of Raygun4PHP, so the changes from this PR cause this error when attempting to use `SendError`:

```
Message: Error: Call to a member function getFile() on null
#0 Raygun4php\RaygunExceptionMessage::BuildErrorTrace called at [/repos/raygun4php/src/Raygun4php/RaygunExceptionMessage.php:27]
#1 Raygun4php\RaygunExceptionMessage::__construct called at [/repos/raygun4php/src/Raygun4php/RaygunMessage.php:27]
#2 Raygun4php\RaygunMessage::build called at [/repos/raygun4php/src/Raygun4php/RaygunClient.php:287]
#3 Raygun4php\RaygunClient::BuildMessage called at [/repos/raygun4php/src/Raygun4php/RaygunClient.php:102]
#4 Raygun4php\RaygunClient::SendError called at [/var/www/html/app/raygunSetup.php:38]
#5 ::{closure} called at [/var/www/html/app/index.php:23]
```

Are you able to update this to work for both `SendError` and `SendException` ?

**Comment by treehousetim** [comment]
Is there a test for this? I ran the test and none of them caught this.

**Comment by Deacon-McIntyre** [comment]
I encountered it via manual testing, but upon running the tests on your branch I do see the `testSendErrorInvokesTransportTransmit` test fails in a similar way. Perhaps something is different in our environments?

```
1) Raygun4php\Tests\RaygunClientTest::testSendErrorInvokesTransportTransmit
Error: Call to a member function getFile() on null

/repos/raygun4php/src/Raygun4php/RaygunExceptionMessage.php:43
/repos/raygun4php/src/Raygun4php/RaygunExceptionMessage.php:27
/repos/raygun4php/src/Raygun4php/RaygunMessage.php:27
/repos/raygun4php/src/Raygun4php/RaygunClient.php:287
/repos/raygun4php/src/Raygun4php/RaygunClient.php:102
/repos/raygun4php/tests/RaygunClientTest.php:263
phpvfscomposer:///repos/raygun4php/vendor/phpunit/phpunit/phpunit:97
```

**Comment by treehousetim** [comment]
I'll look at this and submit a fix. Thanks!

**Comment by treehousetim** [comment]
@Deacon-McIntyre I took another look at this. Running the tests revealed the defect you mentioned.
I have fixed the issue and expanded the feature to include this for both errorExceptions and exceptions.

 I've also added a github action on this repo that will automatically install composer and run tests for code push and pull request opening.  should add a nice safety net and a self-help workflow to PRs

thanks!

**Comment by Deacon-McIntyre** [comment]
Hi @treehousetim , thanks for making those changes, and adding a GitHub action! I can confirm the tests all pass on my end.

However, when manually testing (plain PHP and HTML app, no frameworks), the errors I get coming through to Raygun have a `null` as the first stack trace item, like this:

```
"StackTrace": [
        null,
        {
            "LineNumber": 23,
            "ClassName": "Division by zero",
            "FileName": "/var/www/html/app/index.php",
            "MethodName": ""
        },
        {
            "LineNumber": 23,
            "ClassName": "",
            "FileName": "/var/www/html/app/index.php",
            "MethodName": "{closure}"
        }
    ],
```

Does this happen for you too? Are you able to have another look and see why it might be happening?

**Comment by Deacon-McIntyre** [comment]
Hi @treehousetim , thanks for making those changes, and adding a GitHub action! I can confirm the tests all pass on my end.

However, when manually testing (plain PHP and HTML app, no frameworks), the errors I get coming through to Raygun have a `null` as the first stack trace item, like this:

```
"StackTrace": [
        null,
        {
            "LineNumber": 23,
            "ClassName": "Division by zero",
            "FileName": "/var/www/html/app/index.php",
            "MethodName": ""
        },
        {
            "LineNumber": 23,
            "ClassName": "",
            "FileName": "/var/www/html/app/index.php",
            "MethodName": "{closure}"
        }
    ],
```

Does this happen for you too? Are you able to have another look and see why it might be happening?

**Comment by treehousetim** [comment]
@Deacon-McIntyre - fixed.

**Comment by treehousetim** [comment]
It would be ideal to have a test to ensure there are no empty entries for the stack trace so I've added one.

**Review by Deacon-McIntyre — APPROVED** [review]
Thanks for your efforts here @treehousetim!

**Comment by treehousetim** [comment]
Hi @Deacon-McIntyre , what's the release cadence for a change like this?

**Comment by Deacon-McIntyre** [comment]
@treehousetim If not today it will be out next week

**Pull request merged**
