### PR TITLE
Enhancement: Run phpcs on Travis and ensure PSR-2 compliant code base

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] requires `squizlabs/php_codesniffer` as a `dev` dependency
* [x] runs `phpcs` on Travis
* [x] fixes CS issues

### CODE REVIEW

**Comment by fundead** [comment]
Has the code contained in this PR, #60 and #58 had an integration test run on a site resulting in it successfully sending an error to Raygun, ending up visible in the dashboard as expected, or was it primarily tested against the unit tests?

**Comment by fundead** [comment]
The following commits and PRs look acceptable to enter the QA process. If you could create **one** PR containing the following that would be good:

The entire contents of:

#58 
#60 
#62
#63

From this #59:

Enhancement: Require squizlabs/php_codesniffer as a dev dependency	 8d44fbc
Enhancement: Run phpcs on Travis	 32cca02
Fix: Only one file per class …	 a00cd1d
Fix: PSR-1
Fix: Braces	 55e286a
Fix: Omit closing tags at end of file	 3f6da93
Fix: Expected newline at end of file	 a215ab5
Fix: Closing and opening brace of closures	 e00a83e
Fix: Expected 1 space after semicolon in for loop	 e240601
Fix: Space expected after comma in function call	 57377c5
Fix: FALSE needs to be false	 3166fcd
Fix: Each class must be in a namespace of at least one level	 5572e9f
Fix: File can either define class or cause side effects	 bbcee33
Fix: Bootstrap tests with Composer autoloading	 a459a5e

Due to the breaking changes these will be applied when the provider reaches the v2.0 release. The out-of-spec indentation and column width requirements will most likely be applied at this time too, as they introduce unneeded friction to the maintenance process.

**Comment by dominics** [comment]
@fundead Is there a branch that contains the above BC-breaking PSR2 work that didn't get split out into BC PRs?

Considering sending a few PRs, but I'd much rather base them off the clean code rather than the existing state of things (git whitespace errors, mixed tabs and spaces, mixed 2/4 indentation styles, etc.).

**Comment by dominics** [comment]
I created such a branch (at #76), it's not fully BC for people using the 'copy and require' installation method, even if 2669496 is reverted, as you said. (There are a few other commits in your list that still break BC by removing requires AFAICT?) So, I closed that PR too.

It might be nice to open a 2.0 target branch that we can PR against, if you're willing.

**Pull request closed without merging**
