### PR TITLE
Add ext-json into composer.json and Update guzzle from 6.x to 7.x

### PR DESCRIPTION
**Pull request by m3m0r7**
I added ext-json into composer.json and updated guzzle from 6.x to 7.x.

### CODE REVIEW

**Review by robbieaverill — COMMENTED** [review]
What's the driver for upgrading Guzzle?

**Comment by m3m0r7** [comment]
@robbieaverill 
Thanks for your response.
I'm using it laravel, aws-sdk-php and my organization project.
They are required to use greater than version 7 of GuzzleHttp
(Guzzle version 6 is bugfix-only and It will no longer be maintained. see: https://github.com/guzzle/guzzle/tree/7.0#version-guidance).

- See: https://github.com/aws/aws-sdk-php/blob/master/composer.json#L20
- See: https://github.com/laravel/laravel/blob/master/composer.json#L14

And some libraries:
- league/oauth1-client
- laravel/socialite

Maybe it's better to have the two versions coexist.

**Comment by robbieaverill** [comment]
Okay, thanks for the response. This seems reasonable then, we can release a new minor version with the updated dependency requirement. Would you mind also bumping the minimum PHP version in composer.json and the readme to 7.2?

There's also a linting error: https://travis-ci.org/github/MindscapeHQ/raygun4php/jobs/739556797#L533

**Comment by m3m0r7** [comment]
Okay, I'll fix it 😃

**Review by robbieaverill — APPROVED** [review]
Thanks

**Pull request merged**
